[package]
name = "agc040"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "agc040-a",problem = {platform = "atcoder",contest = "agc040",index = "A"}}
b = {name = "agc040-b",problem = {platform = "atcoder",contest = "agc040",index = "B"}}
c = {name = "agc040-c",problem = {platform = "atcoder",contest = "agc040",index = "C"}}
d = {name = "agc040-d",problem = {platform = "atcoder",contest = "agc040",index = "D"}}
e = {name = "agc040-e",problem = {platform = "atcoder",contest = "agc040",index = "E"}}
f = {name = "agc040-f",problem = {platform = "atcoder",contest = "agc040",index = "F"}}

# dependencies added to new project
[dependencies]
num = '*'
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "agc040-a"
path = "./src/bin/a.rs"

[[bin]]
name = "agc040-b"
path = "./src/bin/b.rs"

[[bin]]
name = "agc040-c"
path = "./src/bin/c.rs"

[[bin]]
name = "agc040-d"
path = "./src/bin/d.rs"

[[bin]]
name = "agc040-e"
path = "./src/bin/e.rs"

[[bin]]
name = "agc040-f"
path = "./src/bin/f.rs"
