[package]
name = "abc156"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "abc156-a",problem = {platform = "atcoder",contest = "abc156",index = "A"}}
b = {name = "abc156-b",problem = {platform = "atcoder",contest = "abc156",index = "B"}}
c = {name = "abc156-c",problem = {platform = "atcoder",contest = "abc156",index = "C"}}
d = {name = "abc156-d",problem = {platform = "atcoder",contest = "abc156",index = "D"}}
e = {name = "abc156-e",problem = {platform = "atcoder",contest = "abc156",index = "E"}}
f = {name = "abc156-f",problem = {platform = "atcoder",contest = "abc156",index = "F"}}

# dependencies added to new project
[dependencies]
num = '*'
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "abc156-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc156-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc156-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc156-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc156-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc156-f"
path = "./src/bin/f.rs"
