[package]
name = "agc003"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "agc003-a",problem = {platform = "atcoder",contest = "agc003",index = "A"}}
b = {name = "agc003-b",problem = {platform = "atcoder",contest = "agc003",index = "B"}}
c = {name = "agc003-c",problem = {platform = "atcoder",contest = "agc003",index = "C"}}
d = {name = "agc003-d",problem = {platform = "atcoder",contest = "agc003",index = "D"}}
e = {name = "agc003-e",problem = {platform = "atcoder",contest = "agc003",index = "E"}}
f = {name = "agc003-f",problem = {platform = "atcoder",contest = "agc003",index = "F"}}

# dependencies added to new project
[dependencies]
itertools = "*"
num = "*"
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "agc003-a"
path = "./src/bin/a.rs"

[[bin]]
name = "agc003-b"
path = "./src/bin/b.rs"

[[bin]]
name = "agc003-c"
path = "./src/bin/c.rs"

[[bin]]
name = "agc003-d"
path = "./src/bin/d.rs"

[[bin]]
name = "agc003-e"
path = "./src/bin/e.rs"

[[bin]]
name = "agc003-f"
path = "./src/bin/f.rs"
