[package]
name = "arc006"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "arc006-a",problem = {platform = "atcoder",contest = "arc006",index = "A"}}
b = {name = "arc006-b",problem = {platform = "atcoder",contest = "arc006",index = "B"}}
c = {name = "arc006-c",problem = {platform = "atcoder",contest = "arc006",index = "C"}}
d = {name = "arc006-d",problem = {platform = "atcoder",contest = "arc006",index = "D"}}

# dependencies added to new project
[dependencies]
num = '*'
permutohedron = "*"
proconio = "*"
superslice = "*"

[[bin]]
name = "arc006-a"
path = "./src/bin/a.rs"

[[bin]]
name = "arc006-b"
path = "./src/bin/b.rs"

[[bin]]
name = "arc006-c"
path = "./src/bin/c.rs"

[[bin]]
name = "arc006-d"
path = "./src/bin/d.rs"
