[package]
name = "kupc2016"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "kupc2016-a",problem = {platform = "atcoder",contest = "kupc2016",index = "A"}}
b = {name = "kupc2016-b",problem = {platform = "atcoder",contest = "kupc2016",index = "B"}}
c = {name = "kupc2016-c",problem = {platform = "atcoder",contest = "kupc2016",index = "C"}}
d = {name = "kupc2016-d",problem = {platform = "atcoder",contest = "kupc2016",index = "D"}}
e = {name = "kupc2016-e",problem = {platform = "atcoder",contest = "kupc2016",index = "E"}}
f = {name = "kupc2016-f",problem = {platform = "atcoder",contest = "kupc2016",index = "F"}}
g = {name = "kupc2016-g",problem = {platform = "atcoder",contest = "kupc2016",index = "G"}}
h = {name = "kupc2016-h",problem = {platform = "atcoder",contest = "kupc2016",index = "H"}}
i = {name = "kupc2016-i",problem = {platform = "atcoder",contest = "kupc2016",index = "I"}}
j = {name = "kupc2016-j",problem = {platform = "atcoder",contest = "kupc2016",index = "J"}}
k = {name = "kupc2016-k",problem = {platform = "atcoder",contest = "kupc2016",index = "K"}}

# dependencies added to new project
[dependencies]
itertools = "*"
num = "*"
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "kupc2016-a"
path = "./src/bin/a.rs"

[[bin]]
name = "kupc2016-b"
path = "./src/bin/b.rs"

[[bin]]
name = "kupc2016-c"
path = "./src/bin/c.rs"

[[bin]]
name = "kupc2016-d"
path = "./src/bin/d.rs"

[[bin]]
name = "kupc2016-e"
path = "./src/bin/e.rs"

[[bin]]
name = "kupc2016-f"
path = "./src/bin/f.rs"

[[bin]]
name = "kupc2016-g"
path = "./src/bin/g.rs"

[[bin]]
name = "kupc2016-h"
path = "./src/bin/h.rs"

[[bin]]
name = "kupc2016-i"
path = "./src/bin/i.rs"

[[bin]]
name = "kupc2016-j"
path = "./src/bin/j.rs"

[[bin]]
name = "kupc2016-k"
path = "./src/bin/k.rs"
