[dependencies]
num = '*'
permutohedron = '*'
proconio = '*'
superslice = '*'

[package]
authors = ['Yosuke Onoue <onoue@likr-lab.com>']
edition = '2018'
name = 'abc069'
version = '0.1.0'

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "abc069-a",problem = {platform = "atcoder",contest = "abc069",index = "A"}}
b = {name = "abc069-b",problem = {platform = "atcoder",contest = "abc069",index = "B"}}
c = {name = "abc069-c",problem = {platform = "atcoder",contest = "abc069",index = "C"}}
d = {name = "abc069-d",problem = {platform = "atcoder",contest = "abc069",index = "D"}}

[[bin]]
name = "abc069-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc069-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc069-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc069-d"
path = "./src/bin/d.rs"
