[package]
name = "arc002"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "arc002-a",problem = {platform = "atcoder",contest = "arc002",index = "A"}}
b = {name = "arc002-b",problem = {platform = "atcoder",contest = "arc002",index = "B"}}
c = {name = "arc002-c",problem = {platform = "atcoder",contest = "arc002",index = "C"}}
d = {name = "arc002-d",problem = {platform = "atcoder",contest = "arc002",index = "D"}}

# dependencies added to new project
[dependencies]
chrono = "*"
itertools = "*"
num = "*"
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"
time = "*"

[[bin]]
name = "arc002-a"
path = "./src/bin/a.rs"

[[bin]]
name = "arc002-b"
path = "./src/bin/b.rs"

[[bin]]
name = "arc002-c"
path = "./src/bin/c.rs"

[[bin]]
name = "arc002-d"
path = "./src/bin/d.rs"
