[package]
name = "agc007"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "agc007-a",problem = {platform = "atcoder",contest = "agc007",index = "A"}}
b = {name = "agc007-b",problem = {platform = "atcoder",contest = "agc007",index = "B"}}
c = {name = "agc007-c",problem = {platform = "atcoder",contest = "agc007",index = "C"}}
d = {name = "agc007-d",problem = {platform = "atcoder",contest = "agc007",index = "D"}}
e = {name = "agc007-e",problem = {platform = "atcoder",contest = "agc007",index = "E"}}
f = {name = "agc007-f",problem = {platform = "atcoder",contest = "agc007",index = "F"}}

# dependencies added to new project
[dependencies]
itertools = "*"
num = "*"
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "agc007-a"
path = "./src/bin/a.rs"

[[bin]]
name = "agc007-b"
path = "./src/bin/b.rs"

[[bin]]
name = "agc007-c"
path = "./src/bin/c.rs"

[[bin]]
name = "agc007-d"
path = "./src/bin/d.rs"

[[bin]]
name = "agc007-e"
path = "./src/bin/e.rs"

[[bin]]
name = "agc007-f"
path = "./src/bin/f.rs"
