[package]
name = "abc126"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "abc126-a",problem = {platform = "atcoder",contest = "abc126",index = "A"}}
b = {name = "abc126-b",problem = {platform = "atcoder",contest = "abc126",index = "B"}}
c = {name = "abc126-c",problem = {platform = "atcoder",contest = "abc126",index = "C"}}
d = {name = "abc126-d",problem = {platform = "atcoder",contest = "abc126",index = "D"}}
e = {name = "abc126-e",problem = {platform = "atcoder",contest = "abc126",index = "E"}}
f = {name = "abc126-f",problem = {platform = "atcoder",contest = "abc126",index = "F"}}

# dependencies added to new project
[dependencies]
itertools = "*"
num = "*"
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "abc126-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc126-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc126-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc126-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc126-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc126-f"
path = "./src/bin/f.rs"
