[dependencies]
permutohedron = "*"
proconio = "*"
superslice = "*"

[package]
authors = ['Yosuke Onoue <onoue@likr-lab.com>']
edition = '2018'
name = 'abc119'
version = '0.1.0'

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "abc119-a",problem = {platform = "atcoder",contest = "abc119",index = "A"}}
b = {name = "abc119-b",problem = {platform = "atcoder",contest = "abc119",index = "B"}}
c = {name = "abc119-c",problem = {platform = "atcoder",contest = "abc119",index = "C"}}
d = {name = "abc119-d",problem = {platform = "atcoder",contest = "abc119",index = "D"}}

[[bin]]
name = "abc119-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc119-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc119-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc119-d"
path = "./src/bin/d.rs"
