[package]
name = "caddi2018"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
c = {name = "caddi2018-c",problem = {platform = "atcoder",contest = "caddi2018",index = "C"}}
d = {name = "caddi2018-d",problem = {platform = "atcoder",contest = "caddi2018",index = "D"}}
e = {name = "caddi2018-e",problem = {platform = "atcoder",contest = "caddi2018",index = "E"}}
f = {name = "caddi2018-f",problem = {platform = "atcoder",contest = "caddi2018",index = "F"}}

# dependencies added to new project
[dependencies]
itertools = "*"
num = "*"
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "caddi2018-c"
path = "./src/bin/c.rs"

[[bin]]
name = "caddi2018-d"
path = "./src/bin/d.rs"

[[bin]]
name = "caddi2018-e"
path = "./src/bin/e.rs"

[[bin]]
name = "caddi2018-f"
path = "./src/bin/f.rs"
