[package]
name = "code-festival-2017-quala"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "code-festival-2017-quala-a",problem = {platform = "atcoder",contest = "code-festival-2017-quala",index = "A"}}
b = {name = "code-festival-2017-quala-b",problem = {platform = "atcoder",contest = "code-festival-2017-quala",index = "B"}}
c = {name = "code-festival-2017-quala-c",problem = {platform = "atcoder",contest = "code-festival-2017-quala",index = "C"}}
d = {name = "code-festival-2017-quala-d",problem = {platform = "atcoder",contest = "code-festival-2017-quala",index = "D"}}
e = {name = "code-festival-2017-quala-e",problem = {platform = "atcoder",contest = "code-festival-2017-quala",index = "E"}}
f = {name = "code-festival-2017-quala-f",problem = {platform = "atcoder",contest = "code-festival-2017-quala",index = "F"}}

# dependencies added to new project
[dependencies]
num = '*'
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "code-festival-2017-quala-a"
path = "./src/bin/a.rs"

[[bin]]
name = "code-festival-2017-quala-b"
path = "./src/bin/b.rs"

[[bin]]
name = "code-festival-2017-quala-c"
path = "./src/bin/c.rs"

[[bin]]
name = "code-festival-2017-quala-d"
path = "./src/bin/d.rs"

[[bin]]
name = "code-festival-2017-quala-e"
path = "./src/bin/e.rs"

[[bin]]
name = "code-festival-2017-quala-f"
path = "./src/bin/f.rs"
