[dependencies]
num = '*'
permutohedron = '*'
proconio = '*'
superslice = '*'

[package]
authors = ['Yosuke Onoue <onoue@likr-lab.com>']
edition = '2018'
name = 'tenka1-2017-beginner'
version = '0.1.0'

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "tenka1-2017-beginner-a",problem = {platform = "atcoder",contest = "tenka1-2017-beginner",index = "A"}}
b = {name = "tenka1-2017-beginner-b",problem = {platform = "atcoder",contest = "tenka1-2017-beginner",index = "B"}}
c = {name = "tenka1-2017-beginner-c",problem = {platform = "atcoder",contest = "tenka1-2017-beginner",index = "C"}}
d = {name = "tenka1-2017-beginner-d",problem = {platform = "atcoder",contest = "tenka1-2017-beginner",index = "D"}}

[[bin]]
name = "tenka1-2017-beginner-a"
path = "./src/bin/a.rs"

[[bin]]
name = "tenka1-2017-beginner-b"
path = "./src/bin/b.rs"

[[bin]]
name = "tenka1-2017-beginner-c"
path = "./src/bin/c.rs"

[[bin]]
name = "tenka1-2017-beginner-d"
path = "./src/bin/d.rs"
