[dependencies]
num = '*'
permutohedron = '*'
proconio = '*'
superslice = '*'

[package]
authors = ['Yosuke Onoue <onoue@likr-lab.com>']
edition = '2018'
name = 'dp'
version = '0.1.0'

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "dp-a",problem = {platform = "atcoder",contest = "dp",index = "A"}}
b = {name = "dp-b",problem = {platform = "atcoder",contest = "dp",index = "B"}}
c = {name = "dp-c",problem = {platform = "atcoder",contest = "dp",index = "C"}}
d = {name = "dp-d",problem = {platform = "atcoder",contest = "dp",index = "D"}}
e = {name = "dp-e",problem = {platform = "atcoder",contest = "dp",index = "E"}}
f = {name = "dp-f",problem = {platform = "atcoder",contest = "dp",index = "F"}}
g = {name = "dp-g",problem = {platform = "atcoder",contest = "dp",index = "G"}}
h = {name = "dp-h",problem = {platform = "atcoder",contest = "dp",index = "H"}}
i = {name = "dp-i",problem = {platform = "atcoder",contest = "dp",index = "I"}}
j = {name = "dp-j",problem = {platform = "atcoder",contest = "dp",index = "J"}}
k = {name = "dp-k",problem = {platform = "atcoder",contest = "dp",index = "K"}}
l = {name = "dp-l",problem = {platform = "atcoder",contest = "dp",index = "L"}}
m = {name = "dp-m",problem = {platform = "atcoder",contest = "dp",index = "M"}}
n = {name = "dp-n",problem = {platform = "atcoder",contest = "dp",index = "N"}}
o = {name = "dp-o",problem = {platform = "atcoder",contest = "dp",index = "O"}}
p = {name = "dp-p",problem = {platform = "atcoder",contest = "dp",index = "P"}}
q = {name = "dp-q",problem = {platform = "atcoder",contest = "dp",index = "Q"}}
r = {name = "dp-r",problem = {platform = "atcoder",contest = "dp",index = "R"}}
s = {name = "dp-s",problem = {platform = "atcoder",contest = "dp",index = "S"}}
t = {name = "dp-t",problem = {platform = "atcoder",contest = "dp",index = "T"}}
u = {name = "dp-u",problem = {platform = "atcoder",contest = "dp",index = "U"}}
v = {name = "dp-v",problem = {platform = "atcoder",contest = "dp",index = "V"}}
w = {name = "dp-w",problem = {platform = "atcoder",contest = "dp",index = "W"}}
x = {name = "dp-x",problem = {platform = "atcoder",contest = "dp",index = "X"}}
y = {name = "dp-y",problem = {platform = "atcoder",contest = "dp",index = "Y"}}
z = {name = "dp-z",problem = {platform = "atcoder",contest = "dp",index = "Z"}}

[[bin]]
name = "dp-a"
path = "./src/bin/a.rs"

[[bin]]
name = "dp-b"
path = "./src/bin/b.rs"

[[bin]]
name = "dp-c"
path = "./src/bin/c.rs"

[[bin]]
name = "dp-d"
path = "./src/bin/d.rs"

[[bin]]
name = "dp-e"
path = "./src/bin/e.rs"

[[bin]]
name = "dp-f"
path = "./src/bin/f.rs"

[[bin]]
name = "dp-g"
path = "./src/bin/g.rs"

[[bin]]
name = "dp-h"
path = "./src/bin/h.rs"

[[bin]]
name = "dp-i"
path = "./src/bin/i.rs"

[[bin]]
name = "dp-j"
path = "./src/bin/j.rs"

[[bin]]
name = "dp-k"
path = "./src/bin/k.rs"

[[bin]]
name = "dp-l"
path = "./src/bin/l.rs"

[[bin]]
name = "dp-m"
path = "./src/bin/m.rs"

[[bin]]
name = "dp-n"
path = "./src/bin/n.rs"

[[bin]]
name = "dp-o"
path = "./src/bin/o.rs"

[[bin]]
name = "dp-p"
path = "./src/bin/p.rs"

[[bin]]
name = "dp-q"
path = "./src/bin/q.rs"

[[bin]]
name = "dp-r"
path = "./src/bin/r.rs"

[[bin]]
name = "dp-s"
path = "./src/bin/s.rs"

[[bin]]
name = "dp-t"
path = "./src/bin/t.rs"

[[bin]]
name = "dp-u"
path = "./src/bin/u.rs"

[[bin]]
name = "dp-v"
path = "./src/bin/v.rs"

[[bin]]
name = "dp-w"
path = "./src/bin/w.rs"

[[bin]]
name = "dp-x"
path = "./src/bin/x.rs"

[[bin]]
name = "dp-y"
path = "./src/bin/y.rs"

[[bin]]
name = "dp-z"
path = "./src/bin/z.rs"
