[dependencies]
num = '*'
permutohedron = '*'
proconio = '*'
superslice = '*'

[package]
authors = ['Yosuke Onoue <onoue@likr-lab.com>']
edition = '2018'
name = 'dp'
version = '0.1.0'
[profile.release]
lto = true
panic = 'abort'
