[dependencies]
num = '*'
permutohedron = '*'
proconio = '*'
superslice = '*'

[package]
authors = ['Yosuke Onoue <onoue@likr-lab.com>']
edition = '2018'
name = 'abc154'
version = '0.1.0'

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "abc154-a",problem = {platform = "atcoder",contest = "abc154",index = "A"}}
b = {name = "abc154-b",problem = {platform = "atcoder",contest = "abc154",index = "B"}}
c = {name = "abc154-c",problem = {platform = "atcoder",contest = "abc154",index = "C"}}
d = {name = "abc154-d",problem = {platform = "atcoder",contest = "abc154",index = "D"}}
e = {name = "abc154-e",problem = {platform = "atcoder",contest = "abc154",index = "E"}}
f = {name = "abc154-f",problem = {platform = "atcoder",contest = "abc154",index = "F"}}

[[bin]]
name = "abc154-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc154-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc154-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc154-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc154-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc154-f"
path = "./src/bin/f.rs"
