[dependencies]
num = '*'
permutohedron = '*'
proconio = '*'
superslice = '*'

[package]
authors = ['Yosuke Onoue <onoue@likr-lab.com>']
edition = '2018'
name = 'abc071'
version = '0.1.0'

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "abc071-a",problem = {platform = "atcoder",contest = "abc071",index = "A"}}
b = {name = "abc071-b",problem = {platform = "atcoder",contest = "abc071",index = "B"}}
c = {name = "abc071-c",problem = {platform = "atcoder",contest = "abc071",index = "C"}}
d = {name = "abc071-d",problem = {platform = "atcoder",contest = "abc071",index = "D"}}

[[bin]]
name = "abc071-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc071-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc071-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc071-d"
path = "./src/bin/d.rs"
