[package]
name = "agc009"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "agc009-a",problem = {platform = "atcoder",contest = "agc009",index = "A"}}
b = {name = "agc009-b",problem = {platform = "atcoder",contest = "agc009",index = "B"}}
c = {name = "agc009-c",problem = {platform = "atcoder",contest = "agc009",index = "C"}}
d = {name = "agc009-d",problem = {platform = "atcoder",contest = "agc009",index = "D"}}
e = {name = "agc009-e",problem = {platform = "atcoder",contest = "agc009",index = "E"}}

# dependencies added to new project
[dependencies]
itertools = "*"
num = "*"
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "agc009-a"
path = "./src/bin/a.rs"

[[bin]]
name = "agc009-b"
path = "./src/bin/b.rs"

[[bin]]
name = "agc009-c"
path = "./src/bin/c.rs"

[[bin]]
name = "agc009-d"
path = "./src/bin/d.rs"

[[bin]]
name = "agc009-e"
path = "./src/bin/e.rs"
