[package]
name = "code-festival-2016-qualc"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "code-festival-2016-qualc-a",problem = {platform = "atcoder",contest = "code-festival-2016-qualc",index = "A"}}
b = {name = "code-festival-2016-qualc-b",problem = {platform = "atcoder",contest = "code-festival-2016-qualc",index = "B"}}
c = {name = "code-festival-2016-qualc-c",problem = {platform = "atcoder",contest = "code-festival-2016-qualc",index = "C"}}
d = {name = "code-festival-2016-qualc-d",problem = {platform = "atcoder",contest = "code-festival-2016-qualc",index = "D"}}
e = {name = "code-festival-2016-qualc-e",problem = {platform = "atcoder",contest = "code-festival-2016-qualc",index = "E"}}

# dependencies added to new project
[dependencies]
num = '*'
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "code-festival-2016-qualc-a"
path = "./src/bin/a.rs"

[[bin]]
name = "code-festival-2016-qualc-b"
path = "./src/bin/b.rs"

[[bin]]
name = "code-festival-2016-qualc-c"
path = "./src/bin/c.rs"

[[bin]]
name = "code-festival-2016-qualc-d"
path = "./src/bin/d.rs"

[[bin]]
name = "code-festival-2016-qualc-e"
path = "./src/bin/e.rs"
