[package]
name = "abc116"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "abc116-a",problem = {platform = "atcoder",contest = "abc116",index = "A"}}
b = {name = "abc116-b",problem = {platform = "atcoder",contest = "abc116",index = "B"}}
c = {name = "abc116-c",problem = {platform = "atcoder",contest = "abc116",index = "C"}}
d = {name = "abc116-d",problem = {platform = "atcoder",contest = "abc116",index = "D"}}

# dependencies added to new project
[dependencies]
num = '*'
permutohedron = "*"
proconio = "*"
superslice = "*"

[[bin]]
name = "abc116-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc116-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc116-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc116-d"
path = "./src/bin/d.rs"
