[package]
name = "arc034"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "arc034-a",problem = {platform = "atcoder",contest = "arc034",index = "A"}}
b = {name = "arc034-b",problem = {platform = "atcoder",contest = "arc034",index = "B"}}
c = {name = "arc034-c",problem = {platform = "atcoder",contest = "arc034",index = "C"}}
d = {name = "arc034-d",problem = {platform = "atcoder",contest = "arc034",index = "D"}}

# dependencies added to new project
[dependencies]
itertools = "*"
num = "*"
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "arc034-a"
path = "./src/bin/a.rs"

[[bin]]
name = "arc034-b"
path = "./src/bin/b.rs"

[[bin]]
name = "arc034-c"
path = "./src/bin/c.rs"

[[bin]]
name = "arc034-d"
path = "./src/bin/d.rs"
