[dependencies]
num = '*'
permutohedron = '*'
proconio = '*'
superslice = '*'

[package]
authors = ['Yosuke Onoue <onoue@likr-lab.com>']
edition = '2018'
name = 'abc101'
version = '0.1.0'

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "abc101-a",problem = {platform = "atcoder",contest = "abc101",index = "A"}}
b = {name = "abc101-b",problem = {platform = "atcoder",contest = "abc101",index = "B"}}
c = {name = "abc101-c",problem = {platform = "atcoder",contest = "abc101",index = "C"}}
d = {name = "abc101-d",problem = {platform = "atcoder",contest = "abc101",index = "D"}}

[[bin]]
name = "abc101-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc101-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc101-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc101-d"
path = "./src/bin/d.rs"
