[package]
name = "practice2"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "practice2-a",problem = {platform = "atcoder",contest = "practice2",index = "A"}}
b = {name = "practice2-b",problem = {platform = "atcoder",contest = "practice2",index = "B"}}
c = {name = "practice2-c",problem = {platform = "atcoder",contest = "practice2",index = "C"}}
d = {name = "practice2-d",problem = {platform = "atcoder",contest = "practice2",index = "D"}}
e = {name = "practice2-e",problem = {platform = "atcoder",contest = "practice2",index = "E"}}
f = {name = "practice2-f",problem = {platform = "atcoder",contest = "practice2",index = "F"}}
g = {name = "practice2-g",problem = {platform = "atcoder",contest = "practice2",index = "G"}}
h = {name = "practice2-h",problem = {platform = "atcoder",contest = "practice2",index = "H"}}
i = {name = "practice2-i",problem = {platform = "atcoder",contest = "practice2",index = "I"}}
j = {name = "practice2-j",problem = {platform = "atcoder",contest = "practice2",index = "J"}}
k = {name = "practice2-k",problem = {platform = "atcoder",contest = "practice2",index = "K"}}
l = {name = "practice2-l",problem = {platform = "atcoder",contest = "practice2",index = "L"}}

# dependencies added to new project
[dependencies]
num = "=0.2.1"
num-bigint = "=0.2.6"
num-complex = "=0.2.4"
num-integer = "=0.1.42"
num-iter = "=0.1.40"
num-rational = "=0.2.4"
num-traits = "=0.2.11"
num-derive = "=0.3.0"
ndarray = "=0.13.0"
nalgebra = "=0.20.0"
alga = "=0.9.3"
libm = "=0.2.1"
rand = { version = "=0.7.3", features = ["small_rng"] }
getrandom = "=0.1.14"
rand_chacha = "=0.2.2"
rand_core = "=0.5.1"
rand_hc = "=0.2.0"
rand_pcg = "=0.2.1"
rand_distr = "=0.2.2"
petgraph = "=0.5.0"
indexmap = "=1.3.2"
regex = "=1.3.6"
lazy_static = "=1.4.0"
ordered-float = "=1.0.2"
ascii = "=1.0.0"
permutohedron = "=0.2.4"
superslice = "=1.0.0"
itertools = "=0.9.0"
itertools-num = "=0.1.3"
maplit = "=1.0.2"
either = "=1.5.3"
im-rc = "=14.3.0"
fixedbitset = "=0.2.0"
bitset-fixed = "=0.1.0"
proconio = { version = "=0.3.6", features = ["derive"] }
text_io = "=0.1.8"
whiteread = "=0.5.0"
rustc-hash = "=1.1.0"
smallvec = "=1.2.0"

[[bin]]
name = "practice2-a"
path = "./src/bin/a.rs"

[[bin]]
name = "practice2-b"
path = "./src/bin/b.rs"

[[bin]]
name = "practice2-c"
path = "./src/bin/c.rs"

[[bin]]
name = "practice2-d"
path = "./src/bin/d.rs"

[[bin]]
name = "practice2-e"
path = "./src/bin/e.rs"

[[bin]]
name = "practice2-f"
path = "./src/bin/f.rs"

[[bin]]
name = "practice2-g"
path = "./src/bin/g.rs"

[[bin]]
name = "practice2-h"
path = "./src/bin/h.rs"

[[bin]]
name = "practice2-i"
path = "./src/bin/i.rs"

[[bin]]
name = "practice2-j"
path = "./src/bin/j.rs"

[[bin]]
name = "practice2-k"
path = "./src/bin/k.rs"

[[bin]]
name = "practice2-l"
path = "./src/bin/l.rs"
