[package]
name = "abc103"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "abc103-a",problem = {platform = "atcoder",contest = "abc103",index = "A"}}
b = {name = "abc103-b",problem = {platform = "atcoder",contest = "abc103",index = "B"}}
c = {name = "abc103-c",problem = {platform = "atcoder",contest = "abc103",index = "C"}}
d = {name = "abc103-d",problem = {platform = "atcoder",contest = "abc103",index = "D"}}

# dependencies added to new project
[dependencies]
itertools = "*"
num = "*"
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "abc103-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc103-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc103-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc103-d"
path = "./src/bin/d.rs"
