[package]
name = "iroha2019-day1"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = {name = "iroha2019-day1-a",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "A"}}
b = {name = "iroha2019-day1-b",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "B"}}
c = {name = "iroha2019-day1-c",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "C"}}
d = {name = "iroha2019-day1-d",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "D"}}
e = {name = "iroha2019-day1-e",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "E"}}
f = {name = "iroha2019-day1-f",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "F"}}
g = {name = "iroha2019-day1-g",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "G"}}
h = {name = "iroha2019-day1-h",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "H"}}
i = {name = "iroha2019-day1-i",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "I"}}
j = {name = "iroha2019-day1-j",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "J"}}
k = {name = "iroha2019-day1-k",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "K"}}
l = {name = "iroha2019-day1-l",problem = {platform = "atcoder",contest = "iroha2019-day1",index = "L"}}

# dependencies added to new project
[dependencies]
itertools = "*"
num = "*"
permutohedron = "*"
proconio = "*"
superslice = "*"
union-find = "*"

[[bin]]
name = "iroha2019-day1-a"
path = "./src/bin/a.rs"

[[bin]]
name = "iroha2019-day1-b"
path = "./src/bin/b.rs"

[[bin]]
name = "iroha2019-day1-c"
path = "./src/bin/c.rs"

[[bin]]
name = "iroha2019-day1-d"
path = "./src/bin/d.rs"

[[bin]]
name = "iroha2019-day1-e"
path = "./src/bin/e.rs"

[[bin]]
name = "iroha2019-day1-f"
path = "./src/bin/f.rs"

[[bin]]
name = "iroha2019-day1-g"
path = "./src/bin/g.rs"

[[bin]]
name = "iroha2019-day1-h"
path = "./src/bin/h.rs"

[[bin]]
name = "iroha2019-day1-i"
path = "./src/bin/i.rs"

[[bin]]
name = "iroha2019-day1-j"
path = "./src/bin/j.rs"

[[bin]]
name = "iroha2019-day1-k"
path = "./src/bin/k.rs"

[[bin]]
name = "iroha2019-day1-l"
path = "./src/bin/l.rs"
